services:
  frontend:
    container_name: frontend-container
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    container_name: backend-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    networks:
      - app-network
    depends_on:
      - db

  reverse-proxy:
    container_name: reverse-proxy-container
    image: nginx:latest
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  db:
    container_name: database-container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge