services:
  frontend:
    container_name: frontend-container
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "9110:80"
    networks:
      - app-network
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]

  reverse-proxy:
    container_name: reverse-proxy-container
    image: nginx:latest
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  db:
    container_name: db-container
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge