#version: "3.8"
version: "3.9"

services:
  #not working - partially 
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

      #not working - at all
  backend: 
    build:
      context: ./src
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "9110-9120:3333"
    networks:
      - app-network
    depends_on:
      - db

  reverse-proxy:
    image: nginx:latest
    #volumes:
    #- ./src/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

 # db:
 #   image: mysql:8
 #    environment:
 #     MYSQL_ROOT_PASSWORD: rootpassword
 #     MYSQL_DATABASE: shop_db
 #     MYSQL_USER: root
 #     MYSQL_PASSWORD: root
 #  ports:
 #     - "3306:3306"
 #   networks:
 #     - app-network
      
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_db
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:       
  app-network:
    driver: bridge

