apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
