# Usando a imagem PHP com Apache
FROM php:7.4-apache

# Habilitar o módulo rewrite do Apache
RUN a2enmod rewrite

# Instalar dependências PHP necessárias
RUN docker-php-ext-install pdo pdo_mysql

# Instalar o Composer (gerenciador de dependências do PHP)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copiar os arquivos do seu código-fonte PHP para o container
COPY . /var/www/html/

# Rodar o Composer para instalar as dependências do projeto
WORKDIR /var/www/html
RUN composer install

# Expor a porta 80 do container (Apache)
EXPOSE 80
