apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-backend
  template:
    metadata:
      labels:
        app: php-backend
    spec:
      containers:
      - name: php-backend
        image: <usuario-dockerhub>/php-backend:latest  # Substitua pelo nome correto da sua imagem
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql-db-service
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: userpassword
        - name: DB_NAME
          value: shop_db
---
apiVersion: v1
kind: Service
metadata:
  name: php-backend-service
spec:
  selector:
    app: php-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
